IT-Academy-BCN/BusinessAssistantBCN-backend

contributors.txt
He añadido mi nombre y github al archivo contributors.txt
=> Actualización del archivo contributors.txt

contributors.txt
=> actualizar archivo contributors.txt

contributors.txt
Correcion Dockerfile y actualización de contributors.txt
=> actualización contributors.txt

BusinessAssistant-opendata/build.gradle
path > BusinessAssistant-opendata\build.gradle
=> añado dependencia org.json

BusinessAssistant-opendata/build.gradle, BusinessAssistant-opendata/resources/application.yml, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/App.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/config/SwaggerConfig.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/config/WebMVCConfiguration.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/controller/EndpointsController.java, BusinessAssistant-opendata/src/main/resources/application.yml, postman/BusinessAssistant-opendata.postman_collection.json
Creación de Endpoints, Swagger v3.0.0 y Postman
=> Creación de Endpoints, Swagger y Postman

contributors.txt
Add Cristoóbal Richart Git Hub address in the file contributors.txt.
=> contributors.txt Cristóbal Richart

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/helper/JsonHelper.java
Created method to serialize to JSON the object JsonNode node.
=> BABCN-32/ JsonHelper: Creación de métodos de serialización

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/controller/OpendataController.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/commercialgalleries/CommercialGaleriesDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/commercialgalleries/CommercialGalleriesResponseDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/largestablishments/LargeStablishmentsDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/CommercialGaleriesService.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/LargeStablishmentsService.java
=> Creadas BABCN-5_and_BABCN-6

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/controller/CommonController.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/largestablishments/LargeStablishmentsDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/LargeStablishmentsService.java
Creación de endpoint /zones
Implementación método getZones()
=> BABCN-52/David/endpoint/zones

contributors.txt
Actualizado contributors.txt con nombre y url github
=> Actualizado contributors.txt

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/LargeEstablishmentsService.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/MarketFairsService.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/MunicipalMarketsService.java
primera parte de circuits breakers
=> circuitebreakers

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/controller/OpendataController.java
CARE! waiting service
return municipalMarketsService.getPageByDistrict(Integer.parseInt(offset), Integer.parseInt(limit), district);
=> BABCN-45/Creación de endpoint municipal-markets/district/{districtId}

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/controller/OpendataController.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/LargeEstablishmentsService.java
He quitado lo que has pedido (JsonHelper, paginación compacta).
Por favor, verifica que estás usando la llamada GET actualizada (con todas las 'es' en /large-establishments) antes de rechazarla.
=> BUG-003 (ex BABCN-37 Filtro por distrito en LargeStablishments - 4o intento)

contributors.txt
Added myself in contributors file.
=> Gustavo Martínez 1# Pull Request

contributors.txt
=> nombre añadido

BusinessAssistant-mydata/src/main/resources/application.properties, BusinessAssistant-mydata/src/main/resources/scripts-mysql/data.sql, BusinessAssistant-mydata/src/main/resources/scripts-mysql/schema.sql
en application.properties lo he configurado para que cargue los esquemas siempre, no estoy segura de que sea lo requerido...
=> BABCN-84 Config: creación de scripts para mysql

BusinessAssistant-mydata/build.gradle, BusinessAssistant-mydata/src/main/java/com/businessassistantbcn/mydata/controller/MydataController.java
En el controller he añadido también los métodos para parsear el offset y el limit.
=> Endpoint Get a search

BusinessAssistant-usermanagement/src/main/java/com/businessassistantbcn/usermanagement/document/Role.java, BusinessAssistant-usermanagement/src/main/java/com/businessassistantbcn/usermanagement/document/User.java, BusinessAssistant-usermanagement/src/main/java/com/businessassistantbcn/usermanagement/dto/Role.java, BusinessAssistant-usermanagement/src/main/java/com/businessassistantbcn/usermanagement/dto/UserCreationDto.java, BusinessAssistant-usermanagement/src/main/java/com/businessassistantbcn/usermanagement/dto/UserDto.java
UserDto.class and UserCreationDto.class where created.
=> Refactor dto package and add new package with Dto classes.

BusinessAssistant-mydata/build.gradle, BusinessAssistant-mydata/src/main/java/com/businessassistantbcn/mydata/controller/GlobalExceptionHandler.java, BusinessAssistant-mydata/src/main/java/com/businessassistantbcn/mydata/controller/MydataController.java, BusinessAssistant-mydata/src/main/java/com/businessassistantbcn/mydata/dto/SaveSearchRequestDto.java
En build.gradle se añaden dependencias para poder usar Hibernate Validator
Se crea GlobalExceptionHandler.java
=> BABCN-84 - validate requestBody in MyDataController.java

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/bigmalls/AddressDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/commercialgalleries/AddressDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/largeestablishments/AddressDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/marketfairs/AddressDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/municipalmarkets/AddressDto.java, BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/municipalmarkets/MunicipalMarketsDto.java
- mueve location dentro de address
- cambia atributo number, ahora street_number
=> BABCN-91 y BABCN-92 - OpenData corrections

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/service/externaldata/LargeEstablishmentsService.java
add new method in LargeEstablishmentService to remove ClassificationData With Marques In FullPath
=> BUG001 - Opendata:Large Establishment

BusinessAssistant-opendata/src/main/java/com/businessassistantbcn/opendata/dto/bcnzones/BcnZonesDto.java, BusinessAssistant-opendata/src/test/java/com/businessassistantbcn/opendata/controller/CommonControllerTest.java, BusinessAssistant-opendata/src/test/java/com/businessassistantbcn/opendata/controller/OpendataControllerTest.java
- simplemente lo he movido de sitio y lo he mantenido tal cual estaba, no sé si hay que hacer algo más relacionado con esta tarea
- en OpenDataControllerTest se utiliza un StarWarsVehicleDto... no sé si esto es intencionado por algo que no entiendo :)
=> BABCN-77 - OpenData CommonControllerTest

BusinessAssistant-gencat/build.gradle, BusinessAssistant-gencat/src/main/resources/application.yml
url's:
http://localhost:8762/swagger-ui-custom.html
http://localhost:8762/api-docs
=> #339 Adicion de Swagger a gencat

BusinessAssistant-opendata/build.gradle, BusinessAssistant-opendata/src/main/resources/application.yml
url's:
http://localhost:8762/api-docs
http://localhost:8762/swagger-ui-custom.html
=> Adicion de Swagger a Opendata #340

BusinessAssistant-gencat/build.gradle, BusinessAssistant-gencat/src/main/java/com/businessassistantbcn/gencat/config/HttpSecurityConfig.java, BusinessAssistant-gencat/src/main/java/com/businessassistantbcn/gencat/config/SecurityPropertiesConfig.java, BusinessAssistant-gencat/src/main/java/com/businessassistantbcn/gencat/controller/GencatController.java, BusinessAssistant-gencat/src/main/java/com/businessassistantbcn/gencat/security/JwtAuthenticationFilter.java, BusinessAssistant-gencat/src/main/resources/application.yml
- security dependencies added
- security.datasource variables
- spring.profiles
=> Closes #375 - Gencat: security filter added & profiles

BusinessAssistant-usermanagement/build.gradle, BusinessAssistant-usermanagement/src/main/resources/application.yml
url's
http://localhost:8763/swagger-ui-custom.html
http://localhost:8763/api-docs
Se debe deshabilitar Spring Security para poder acceder a Swagger, de lo contrario pedirá el token de autenticación
Nota: (cuando este aprobada la PR con el perfil dev que tiene deshabilitada la seguridad, se puede probar desde dev)
=> #341 Adicion de Swagger a Usermanagement
